FROM ubuntu:18.04

MAINTAINER EtricKombat 

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip
RUN apt-get update -y
RUN apt-get install -qqy x11-apps -y
COPY . /app
WORKDIR /app

RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get install systemd -y
RUN timedatectl set-timezone Asia/Kolkata




RUN apt-get install python3-tk -y
RUN pip3 install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["main.py"]
